### ISSUE TITLE
Unicode problem with searchlists/ini-reader

### ISSUE THREAD

**Issue by fdemmer** [fdemmer/Picard-Last.fm.ng-Plugin#11]
it seems there is a problem with unicode characters in searchlists.

Joseph reports:

```
W: 20:32:02 Plugin directory 'C:\\Program Files (x86)\\MusicBrainz Picard\\plugins' doesn't exist

I: 20:32:02 Last.fm.ng - host: ws.audioscrobbler.com:443

I: 20:32:02 Last.fm.ng - key: 0a8b8f968b285654f9b4f16e8e33f2ee

I: 20:32:02 Last.fm.ng - collect_unused: False

I: 20:32:02 Last.fm.ng - ignore_feat_artists: False

I: 20:32:02 Last.fm.ng - default_unknown: Unknown

E: 20:32:02 Plugin 'lastfmng' : Traceback (most recent call last):

File "picard\plugin.pyo", line 191, in load_plugin

File "C:\Users\Joseph\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\__init__.py", line 64, in <module>

File "C:\Users\Joseph\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 13, in <module>

File "C:\Users\Joseph\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\settings.py", line 230, in <module>

File "C:\Users\Joseph\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\settings.py", line 95, in __init__

File "C:\Users\Joseph\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\settings.py", line 159, in load_searchlist

File "C:\Users\Joseph\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\helpers\searchlists.py", line 52, in __init__

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 195: ordinal not in range(128)
```

on windows with picard 1.3.2

**Comment by fdemmer** [comment]
is fixed in picard-14 branch, https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/commit/04f170b43369aa8bd267c110d81598b3abad920a
