### ISSUE TITLE
Errors with 0.14

### ISSUE THREAD

**Issue by RyanThaDude** [fdemmer/Picard-Last.fm.ng-Plugin#21]
I just updated from 0.12 to 0.14 of the plugin and I'm now seeing this error in the logs and causes MB to hang on loading the album.

```
I: 23:52:42 Last.fm.ng - host: ws.audioscrobbler.com:443
I: 23:52:42 Last.fm.ng - key: [*** removed ***]
I: 23:52:42 Last.fm.ng - collect_unused: False
I: 23:52:42 Last.fm.ng - ignore_feat_artists: False
I: 23:52:42 Last.fm.ng - default_unknown: Unknown
I: 23:52:42 Last.fm.ng - enabled categories: grouping (1), genre (4), mood (4), occasion (4), category (4), country (2), city (1), decade (1)
E: 23:52:59 Traceback (most recent call last):
  File "picard\album.pyo", line 136, in _parse_release
  File "picard\metadata.pyo", line 311, in run_album_metadata_processors
  File "picard\plugin.pyo", line 273, in run
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\__init__.py", line 93, in album_metadata_processor
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 352, in request_album_toptags
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 226, in dispatch
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 260, in add_request
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\compat.py", line 71, in get
TypeError: get() got an unexpected keyword argument 'queryargs'

E: 23:53:00 Traceback (most recent call last):
  File "picard\album.pyo", line 136, in _parse_release
  File "picard\metadata.pyo", line 311, in run_album_metadata_processors
  File "picard\plugin.pyo", line 273, in run
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\__init__.py", line 93, in album_metadata_processor
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 352, in request_album_toptags
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 226, in dispatch
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 260, in add_request
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\compat.py", line 71, in get
TypeError: get() got an unexpected keyword argument 'queryargs'

E: 23:53:01 Traceback (most recent call last):
  File "picard\album.pyo", line 136, in _parse_release
  File "picard\metadata.pyo", line 311, in run_album_metadata_processors
  File "picard\plugin.pyo", line 273, in run
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\__init__.py", line 93, in album_metadata_processor
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 352, in request_album_toptags
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 226, in dispatch
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 260, in add_request
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\compat.py", line 71, in get
TypeError: get() got an unexpected keyword argument 'queryargs'

E: 23:53:02 Traceback (most recent call last):
  File "picard\album.pyo", line 136, in _parse_release
  File "picard\metadata.pyo", line 311, in run_album_metadata_processors
  File "picard\plugin.pyo", line 273, in run
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\__init__.py", line 93, in album_metadata_processor
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 352, in request_album_toptags
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 226, in dispatch
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 260, in add_request
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\compat.py", line 71, in get
TypeError: get() got an unexpected keyword argument 'queryargs'

E: 23:53:03 Traceback (most recent call last):
  File "picard\album.pyo", line 136, in _parse_release
  File "picard\metadata.pyo", line 311, in run_album_metadata_processors
  File "picard\plugin.pyo", line 273, in run
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\__init__.py", line 93, in album_metadata_processor
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 352, in request_album_toptags
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 226, in dispatch
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 260, in add_request
  File "C:\Users\Ryan\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\compat.py", line 71, in get
TypeError: get() got an unexpected keyword argument 'queryargs'
```

I made sure I removed all files from 0.12 during the upgrade.

**Comment by RyanThaDude** [comment]
It's working now. I think it might have been an issue of running an older nightly version. I upgraded to the most recent version and it's working.
