### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by Sophobiaful** [fdemmer/Picard-Last.fm.ng-Plugin#43]
Everytime I try and install this plugin I receive this error.

E: 17:12:55 Plugin 'lastfmng' : Traceback (most recent call last):
  File "picard\plugin.pyo", line 299, in load_plugin
  File "C:\Users\USER\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\__init__.py", line 64, in <module>
  File "C:\Users\USER\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 2, in <module>
  File "C:\Users\USER\AppData\Roaming\MusicBrainz\Picard\plugins\lastfmng\logging.py", line 7, in <module>
AttributeError: 'module' object has no attribute 'Handler'

I've tried downgrading Picard, but I keep getting this same error. I've tried installing the plugin manually and through Picard.

#### Environment and versions

* Operating system: Windows 8.1
* Picard version(s): 1.4, 1.4.2
* Plugin version(s) or commit hash: v0.15, v2.0rc1

#### How to reproduce the problem

Everytime I've tried to install the plugin, this error occurs.

**Comment by fdemmer** [comment]
- v2.0rc1 is not compatibe with picard 1.3 or 1.4!
- the error is similar to the one reported in #44, that happens when using v2.0rc1 with picard 1.4.2, which is expected
- i cannot reproduce the issue with v0.15 and picard 1.4.2
