### ISSUE TITLE
Picard Crash - AttributeError: 'QByteArray' object has no attribute 'lfm'

### ISSUE THREAD

**Issue by Enverex** [fdemmer/Picard-Last.fm.ng-Plugin#52]
Picard 2.0.1. Looks like a failed lookup can break this plugin which in turn crashes the entire of Picard. Terminal output which seems pretty comprehensive is below:

	E: 13:01:54,603 /usr/lib/python3.7/site-packages/picard/webservice/__init__._handle_reply:372: Network request error for https://ws.audioscrobbler.com:443/2.0/?method=track.gettoptags&track=Video: Rehab / Back to Black / You Know I'm No Good / Tears Dry on Their Own / Love Is a Losing Game&artist=Amy Winehouse&api_key=0a8b8f968b285654f9b4f16e8e33f2ee: Error transferring https://ws.audioscrobbler.com:443/2.0/?method=track.gettoptags&track=Video: Rehab / Back to Black / You Know I'm No Good / Tears Dry on Their Own / Love Is a Losing Game&artist=Amy Winehouse&api_key=0a8b8f968b285654f9b4f16e8e33f2ee - server replied: Bad Request (QT code 302, HTTP code 400)
	E: 13:01:54,605 /root/.config/MusicBrainz/Picard/plugins/lastfmng/plugin.decorate:304: Problem in handler:
	Traceback (most recent call last):
	  File "/root/.config/MusicBrainz/Picard/plugins/lastfmng/plugin.py", line 301, in decorate
		func(*args, **kwargs)
	  File "/root/.config/MusicBrainz/Picard/plugins/lastfmng/plugin.py", line 407, in handle_toptags
		lfm = data.lfm.pop()
	AttributeError: 'QByteArray' object has no attribute 'lfm'

	Traceback (most recent call last):
	  File "/usr/lib/python3.7/site-packages/picard/webservice/__init__.py", line 426, in _process_reply
		self._handle_reply(reply, request)
	  File "/usr/lib/python3.7/site-packages/picard/webservice/__init__.py", line 388, in _handle_reply
		handler(reply.readAll(), reply, error)
	  File "/root/.config/MusicBrainz/Picard/plugins/lastfmng/plugin.py", line 301, in decorate
		func(*args, **kwargs)
	  File "/root/.config/MusicBrainz/Picard/plugins/lastfmng/plugin.py", line 407, in handle_toptags
		lfm = data.lfm.pop()
	AttributeError: 'QByteArray' object has no attribute 'lfm'
	Aborted

**Comment by Enverex** [comment]
Seems to work fine, thanks!
