### ISSUE TITLE
Doesn't install on MusicBrainz Picard 2.0.2 on Ubuntu

### ISSUE THREAD

**Issue by ApJota** [fdemmer/Picard-Last.fm.ng-Plugin#53]
_[Add a short description or summary of the problem you are experiencing, feature you want or question you have.]_

#### Environment and versions

Linux 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
MusicBrainz Picard 2.0.2
Lastfmng 2.0.1

When I try to install the errors bellow occur:

E: 08:24:39,533 /usr/lib/picard/picard/plugin.load_plugin:349: Plugin 'lastfmng' : Traceback (most recent call last):
  File "/home/jota/.config/MusicBrainz/Picard/plugins/lastfmng.zip/lastfmng/vendor/configparser.py", line 1135, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'global'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/picard/picard/plugin.py", line 324, in load_plugin
    plugin_module = importer.load_module(_PLUGIN_MODULE_PREFIX + name)
  File "/home/jota/.config/MusicBrainz/Picard/plugins/lastfmng.zip/lastfmng/__init__.py", line 69, in <module>
    from .plugin import LastFMTagger
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/jota/.config/MusicBrainz/Picard/plugins/lastfmng.zip/lastfmng/plugin.py", line 13, in <module>
    from . import settings
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/jota/.config/MusicBrainz/Picard/plugins/lastfmng.zip/lastfmng/settings.py", line 46, in <module>
    LASTFM_HOST = config.get('global', 'lastfm_host')
  File "/home/jota/.config/MusicBrainz/Picard/plugins/lastfmng.zip/lastfmng/vendor/configparser.py", line 778, in get
    d = self._unify_values(section, vars)
  File "/home/jota/.config/MusicBrainz/Picard/plugins/lastfmng.zip/lastfmng/vendor/configparser.py", line 1138, in _unify_values
    raise NoSectionError(section)
picard.plugins.lastfmng.vendor.configparser.NoSectionError: No section: 'global'

**Comment by ApJota** [comment]
It worked after unpacking folder. Although most plugins are compressed.
