### ISSUE TITLE
Issues with picard 2.9

### ISSUE THREAD

**Issue by khaoohs** [fdemmer/Picard-Last.fm.ng-Plugin#71]
After updating to picard 2.9, when refreshing information on a release, it never finsihes.
The below error message is seen in the info tab.

Traceback (most recent call last):
  File "album.py", line 205, in _run_album_metadata_processors
  File "metadata.py", line 679, in run_album_metadata_processors
  File "plugin.py", line 265, in run
  File "C:\Users\khaoohs\AppData\Local\MusicBrainz\Picard\plugins\lastfmng\__init__.py", line 98, in album_metadata_processor
    lfmws.request_all_artist_toptags()
  File "C:\Users\khaoohs\AppData\Local\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 398, in request_all_artist_toptags
    self.dispatch('all_artist', params)
  File "C:\Users\khaoohs\AppData\Local\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 213, in dispatch
    self.add_task(partial(self.handle_cached_toptags, tagtype, query))
  File "C:\Users\khaoohs\AppData\Local\MusicBrainz\Picard\plugins\lastfmng\plugin.py", line 267, in add_task
    request=WSRequest(
TypeError: __init__() got an unexpected keyword argument 'host'

#### Environment and versions

* Operating system: Windows 2016
* Picard version(s): 2.9
* Plugin version(s) or commit hash: 2.0.4

**Comment by fdemmer** [comment]
duplicate #70
